### ISSUE TITLE
电视音量控制存在问题

### ISSUE THREAD

**Issue by axelburks** [shaonianzhentan/xiaomi_tv#11]
xiaomi.tv.rmh1
制造商：xiaomi
固件：4.2.4_257

<img width="404" alt="截屏2022-01-31 下午11 54 31" src="https://user-images.githubusercontent.com/11376445/151827481-135a8139-4bf5-46a9-83e9-7d9dc8bebefd.png">

当通过音量音量条调节音量到小于等于 15 时，会按照一定比例并乘以100进行调节，比如，滑动到10，而电视音量实际上会变成65，感觉应该是下面这个地方造成的
<img width="753" alt="截屏2022-01-31 下午11 59 56" src="https://user-images.githubusercontent.com/11376445/151828744-35b06608-a006-4b4d-bc72-a3b47e8c338e.png">

https://github.com/al-one/hass-xiaomi-miot/blob/master/custom_components/xiaomi_miot/media_player.py 这个插件是正常的，仅供参考

**Comment by shaonianzhentan** [comment]
因为小米盒子的最大音量是15，所以这里做了适配。小米电视的暂时还没有进行适配
