### ISSUE TITLE
能否通过 HDMI 信号判断是否关闭电视

### ISSUE THREAD

**Issue by Dukewill** [shaonianzhentan/xiaomi_tv#19]
因为电视不支持 HDMI CEC，电视盒子关机后电视并不会自动关机，所以想通过自动化判断 HDMI 信号状态决定是否关机。

想请教下插件或者项目中开/关机 Blueprint 能不能支持 HDMI 状态的监测从而实现自动化。

感谢！

**Comment by shaonianzhentan** [comment]
无法监测外部控制电视盒子的任何事件，仅支持在HA中控制监测

**Comment by Dukewill** [comment]
> 无法监测外部控制电视盒子的任何事件，仅支持在HA中控制监测

感谢回复。

这里不是监测外部控制电视盒子的事件，而是电视本身 HDMI 的输入状态。试了下 Blueprint 里的那些接口动作好像都不行。

**Comment by shaonianzhentan** [comment]
我的使用方式（仅供参考）
HA打开小米盒子 -> 触发开机事件 -> 然后自行通过各种方式打开显示器&盒子
HA关闭小米盒子 -> 关闭盒子 -> 触发关机事件 -> 关闭显示器

蓝图中的两个事件，就是自定义的后续操作

比如我的显示器不能关闭，我就用一个智能插座，关机后，延时5秒断开电源，然后显示器就关闭了

**Comment by Dukewill** [comment]
> 我的使用方式（仅供参考）
> 
> HA打开小米盒子 -> 触发开机事件 -> 然后自行通过各种方式打开显示器&盒子
> 
> HA关闭小米盒子 -> 关闭盒子 -> 触发关机事件 -> 关闭显示器
> 
> 
> 
> 蓝图中的两个事件，就是自定义的后续操作
> 
> 
> 
> 比如我的显示器不能关闭，我就用一个智能插座，关机后，延时5秒断开电源，然后显示器就关闭了

感谢您的启发
