### ISSUE TITLE
配置好以后没有 xiaomi_tv.adb_command 这个service

### ISSUE THREAD

**Issue by lijiazhiren** [shaonianzhentan/xiaomi_tv#20]
音量加减 开关 信号源 adb都可以正常使用
只是在服务里怎么都没有找到xiaomi_tv.adb_command这个service
不知道是哪里的问题

**Comment by shaonianzhentan** [comment]
1. 先将小米电视ADB模式开启
2. 在HomeAsssitant集成中添加`android_tv`组件（通过这个组件进行关联配对）
3. 配对成功后，重启HomeAssistant会自动加载这个服务

**Comment by lijiazhiren** [comment]
> 1. 先将小米电视ADB模式开启
> 2. 在HomeAsssitant集成中添加`android_tv`组件（通过这个组件进行关联配对）
> 3. 配对成功后，重启HomeAssistant会自动加载这个服务

我新装了一个ha专门用来测试这个
结果还是跟前面的一样 没有能找到xiaomi_tv.adb_command
会不会跟安卓的系统版本有关?
不知道怎么看小米tv的安卓版本 现在只知道mitv os 是224

**Comment by lijiazhiren** [comment]
> 

我更新了新版以后已经可以找到xiaomi_tv.adb_command了
我需要自动化切换hdmi 
在ha服务里我尝试了不少命令 大多数都可以使用
只是hdmi的都不可以
大佬可以给个命令代码吗

**Comment by shaonianzhentan** [comment]
关于adb命令我并不了解怎么切换HDMI，你需要自己去查找相关文档

**Comment by lijiazhiren** [comment]
> 关于adb命令我并不了解怎么切换HDMI，你需要自己去查找相关文档

这个组件还有别的方法能切换HDMI吗?
