### ISSUE TITLE
HA更新到5.0不能用了

### ISSUE THREAD

**Issue by lwh201314** [shaonianzhentan/xiaomi_tv#21]
此错误来自自定义集成。

Logger: homeassistant.config_entries
Source: custom_components/xiaomi_tv/__init__.py:11
Integration: 小米电视 (documentation)
First occurred: 15:18:52 (2 occurrences)
Last logged: 15:18:52

Error setting up entry 192.168.1.231 for xiaomi_tv
Error setting up entry 192.168.1.233 for xiaomi_tv
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/xiaomi_tv/__init__.py", line 11, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by jiuyaozhuce** [comment]
一样，我的更新后也出现了bug

**Comment by zgjsntsm** [comment]
+1

**Comment by shaonianzhentan** [comment]
已修复
