### ISSUE TITLE
请问您是怎么实现小米电视开机的

### ISSUE THREAD

**Issue by leoujz** [shaonianzhentan/xiaomi_tv#3]
我测试了,关机是可以控制成功的,但是关机之后,貌似小米电视就从WIFI断开了.

是需要在电视上做什么设置吗?

**Comment by shaonianzhentan** [comment]
> 我测试了,关机是可以控制成功的,但是关机之后,貌似小米电视就从WIFI断开了.
> 
> 是需要在电视上做什么设置吗?

请看视频：https://www.bilibili.com/video/BV1534y1Q7Gy/

**Comment by Tao173** [comment]
> 我测试了,关机是可以控制成功的,但是关机之后,貌似小米电视就从WIFI断开了.
> 
> 是需要在电视上做什么设置吗?

可以使用博联的遥控器或者小米的空调伴侣（带遥控器那个）学开机红外码利用ha自动化接入开机，小米电视蓝牙遥控器的也可以，其实电视内置红外接收器了的。实测完美，另外如果有小爱的话，更简单利用[https://github.com/al-one/hass-xiaomi-miot](url)项目执行脚本实现小爱同学静默执行电视开机。
