### ISSUE TITLE
请问有什么办法，homekit 只显示小米电视的开关，不显示多余的快捷指令了

### ISSUE THREAD

**Issue by llleonzhao** [shaonianzhentan/xiaomi_tv#4]
![IMG_3444](https://user-images.githubusercontent.com/4151445/133914285-89baf41b-bcb4-4d45-95f1-c182fc82fb9d.jpg)

这个快捷指定，经常性的会失败，里面都是空的。所以我这边想直接去掉这些配置，请问有办法吗

**Comment by shaonianzhentan** [comment]
你可以fork一份，把获取app的代码注释掉就好了

**Comment by llleonzhao** [comment]
好的，我这边试试
